//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQHomeWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grade()
        {
            this.Remarks = new HashSet<Remark>();
        }
    
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public int AdminId { get; set; }
        public int Sustainability { get; set; }
        public int Workflow { get; set; }
        public int SzstPromotion { get; set; }
        public int SupportFromOtherOrganizations { get; set; }
        public int Innovation { get; set; }
        public int ImportanceForOtherStudents { get; set; }
        public int SubjectiveOpinion { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remark> Remarks { get; set; }
    }
}
